name: Publish version

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # we need to fetch full git in-order for lerna to
      # detect rc count
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - name: Install packages
        run: yarn install
        
      - name: Test
        run: npm version patch --no-git-tag-version
        
      - name: Push tag
        run: git config --global user.name "vydo2tiki" && git config --global user.email vy.do2@tiki.vn

      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Push tag
        run: git push && git push --tag
  
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
