name: Publish version

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # we need to fetch full git in-order for lerna to
      # detect rc count
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - name: Install packages
        run: yarn install
        
      - name: Test
        run: npm version patch --no-git-tag-version
        
      - name: Config
        run: git config --global user.name "github action" && git config --global user.email vy.do2@tiki.vn
  
      - name: Push 
        run: git add . && git commit -m "new version" && git push
        
